### ISSUE TITLE
Worked the first time I installed it, refreshed Discord and now is no longer working

### ISSUE THREAD

**Issue by Freeplayg** [cyyynthia/toprole-everywhere#1]
Error in output (Updated with the correct error this time, oops.):
![](https://i.imgur.com/yWA4L4D.png)

**Comment by Freeplayg** [comment]
~~^ I have realized that is the wrong error.~~
Updated original post, sorry, don't know how GitHub works D:

**Comment by cyyynthia** [comment]
That's odd, I don't have this issue and I don't seem to be able to reproduce it whatsoever
What plugins do you have installed?

**Comment by Freeplayg** [comment]
I've disabled every plugin except this one and the ones that are required for Powercord to work. 
The same error happens when I refresh Discord.
